In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data_jobs.csv')
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [18]:
df.sample(10, random_state=2)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
631903,Data Analyst,Data Analyst Staff - Level 4,"Fort Worth, TX",via ZipRecruiter,Full-time,False,"Texas, United States",2023-07-28 12:01:23,True,False,United States,NaN,NaN,NaN,Lockheed Martin,NaN,NaN
675347,Business Analyst,IT BUSINESS SYSTEMS ANALYST SENIOR,"Birmingham, AL",via KFOR Jobs,Full-time,False,Georgia,2023-03-26 10:39:19,False,True,United States,NaN,NaN,NaN,First Horizon Bank,"['sql', 'c', 'sql server', 'db2', 'oracle', 'h...","{'cloud': ['oracle'], 'databases': ['sql serve..."
246258,Senior Data Analyst,"Senior Data Analyst, Business Intelligence (Mo...","Dublin, Ireland",via Hitmarker,Contractor,False,Ireland,2023-04-12 07:28:26,True,False,Ireland,NaN,NaN,NaN,2K,"['sql', 'snowflake', 'aws', 'tableau', 'looker...","{'analyst_tools': ['tableau', 'looker', 'power..."
242366,Data Engineer,Data Engineer,"Portland, OR",via KHON2 Jobs,Full-time,False,Georgia,2023-06-08 07:47:42,False,True,United States,hour,NaN,80.0,VanderHouwen,"['python', 'postgresql', 'aws', 'hadoop', 'lin...","{'cloud': ['aws'], 'databases': ['postgresql']..."
588047,Data Analyst,Data Analyst,France,via BeBee,Full-time,False,France,2023-01-05 09:40:31,True,False,France,NaN,NaN,NaN,GAMIVO S.A.,"['sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
558190,Data Analyst,Data Analyst,"Santiago, Chile",via BeBee Chile,Full-time,False,Chile,2023-06-29 05:13:43,True,False,Chile,NaN,NaN,NaN,Mccann Worldgroup,"['sql', 'databricks']","{'cloud': ['databricks'], 'programming': ['sql']}"
396993,Business Analyst,Business Intelligence Analyst,"Stockholm, Sweden",via Monster.se,Full-time,False,Sweden,2023-01-27 19:14:28,True,False,Sweden,NaN,NaN,NaN,Gazella,"['julia', 'power bi']","{'analyst_tools': ['power bi'], 'programming':..."
434658,Data Engineer,DataStage Data Engineer,"Amsterdam, Netherlands",via LinkedIn,Full-time,False,Netherlands,2023-01-18 16:27:12,False,False,Netherlands,NaN,NaN,NaN,Selby Jennings,"['sql', 'shell', 'python', 'oracle', 'azure', ...","{'cloud': ['oracle', 'azure'], 'os': ['linux',..."
785194,Data Analyst,Data Analyst,Indonesia,via Lokersby.id,Full-time,False,Indonesia,2023-07-22 06:46:40,False,False,Indonesia,NaN,NaN,NaN,PT Istana Mobil Surabaya Indah,NaN,NaN
72133,Data Scientist,Data Scientist,"Lausanne, Switzerland",via Recruit.net,Full-time,False,Switzerland,2023-09-05 00:26:33,False,False,Switzerland,NaN,NaN,NaN,Randstad,"['python', 'azure', 'plotly', 'matplotlib', 'n...","{'cloud': ['azure'], 'libraries': ['plotly', '..."

In [19]:
df_original = pd.read_csv('data_jobs.csv')
df_original

In [21]:
df_original

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [23]:
df_altered = df_original

In [25]:
median_salary = df_altered['salary_year_avg'].median()
print(median_salary)

115000.0

In [26]:
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[:10, 'salary_year_avg']

0     115000.0
1     115000.0
2     115000.0
3     115000.0
4     115000.0
5     115000.0
6     115000.0
7     115000.0
8     115000.0
9     115000.0
10    115000.0
Name: salary_year_avg, dtype: float64

In [27]:
df_original.loc[:10, 'salary_year_avg']

0     115000.0
1     115000.0
2     115000.0
3     115000.0
4     115000.0
5     115000.0
6     115000.0
7     115000.0
8     115000.0
9     115000.0
10    115000.0
Name: salary_year_avg, dtype: float64

In [30]:
id(df_original) == id(df_altered)

True

In [31]:
df_original = pd.read_csv('data_jobs.csv')

In [32]:
df_altered = df_original.copy()

In [33]:
print('ID of df_original:               ', id(df_original))
print('ID of df_altered:                ', id(df_altered))
print('Are the 2 dsataframes the same?  ', id(df_original) == id(df_altered))

ID of df_original:                2580231823248
ID of df_altered:                 2580269333264
Are the 2 dsataframes the same?   False

In [39]:
df = pd.read_csv('data_jobs.csv')
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

df_copy = df.copy()
df_copy = df_copy.dropna(subset=['salary_year_avg'])
df_copy

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",NaN,NaN
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

In [45]:
df_random = df.sample(frac=0.1)
df_random.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
611994,Senior Data Scientist,Senior Data Scientist with Security Clearance,"Herndon, VA",via Trabajo.org,Full-time,False,Georgia,2023-06-28 13:19:09,False,True,United States,NaN,NaN,NaN,Noblis,"['python', 'scala', 'r', 'java', 'neo4j', 'aws...","{'analyst_tools': ['splunk'], 'cloud': ['aws']..."
703159,Data Scientist,Data Scientist (w/Active Secret Clearance),"Tampa, FL",via Startup Jobs,Full-time,False,Georgia,2023-08-08 04:31:33,False,False,United States,NaN,NaN,NaN,Redhorse,"['python', 'r', 'scala', 'sql']","{'programming': ['python', 'r', 'scala', 'sql']}"
567592,Data Engineer,Principal Data Engineer,"Concord, NH",via BeBee,Full-time and Part-time,False,"Texas, United States",2023-12-25 09:02:58,False,True,United States,year,150000.0,NaN,Capital One,"['java', 'scala', 'python', 'nosql', 'sql', 'm...","{'cloud': ['redshift', 'snowflake', 'aws', 'az..."
39087,Senior Data Analyst,Data Remediation Senior Analyst,"Heredia Province, Heredia, Costa Rica",via BeBee Costa Rica,Full-time,False,Costa Rica,2023-11-01 06:37:05,False,False,Costa Rica,NaN,NaN,NaN,Citi,['power bi'],{'analyst_tools': ['power bi']}
257283,Data Scientist,Intermediate Data Scientist - Johannesburg - u...,"Johannesburg, South Africa",via Pnet,Full-time,False,South Africa,2023-12-14 07:14:05,False,False,South Africa,NaN,NaN,NaN,E-Merge IT Recruitment,"['python', 'r', 'sql', 'sas', 'sas', 'aws', 'p...","{'analyst_tools': ['sas', 'power bi'], 'cloud'..."

In [46]:
df = pd.read_csv('data_jobs.csv')
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])
df_copy = df.copy()

median_salary = df_copy['salary_year_avg'].median()

df_copy['salary_year_avg'] = df_copy['salary_year_avg'].fillna(median_salary)

df_copy.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,115000.0,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,115000.0,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,115000.0,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,115000.0,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,115000.0,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."