In [27]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data_jobs.csv')
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [4]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [9]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()

def projected_salary(salary):
    return salary * 1.03

df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [10]:
df_salary['salary_year_inflated'] = df['salary_year_avg'].apply(lambda salary: salary * 1.03)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [28]:
import ast

ast.literal_eval(df['job_skills'][1])

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [22]:
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)

df['job_skills'] = df['job_skills'].apply(clean_list)

In [24]:
df['job_skills'][1]

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [29]:
df['job_skills'] = df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else skill_list)

In [32]:
type(df['job_skills'][10])
df['job_skills'][10]

['python', 'databricks', 'azure', 'spark']

In [34]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary: salary*1.03)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [38]:
def projected_salary(row):
    if 'Senior' in row['job_title_short']:
        return row['salary_year_avg'] * 1.05
    else:
        return row['salary_year_avg'] * 1.03

df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis=1)

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']].head(20)

          job_title_short  salary_year_avg  salary_year_inflated
28         Data Scientist         109500.0             112785.00
77          Data Engineer         140000.0             144200.00
92          Data Engineer         120000.0             123600.00
100        Data Scientist         228222.0             235068.66
109          Data Analyst          89000.0              91670.00
116        Data Scientist         114000.0             117420.00
146         Data Engineer         129500.0             133385.00
180          Data Analyst          90250.0              92957.50
212        Data Scientist         157500.0             162225.00
257        Data Scientist         103128.0             106221.84
307         Data Engineer         185000.0             190550.00
339         Data Engineer         195000.0             200850.00
380         Data Engineer          97500.0             100425.00
388         Data Engineer          89000.0              91670.00
410          Data Analyst         133285.0             137283.55
450        Data Scientist         157500.0             162225.00
495  Senior Data Engineer         168500.0             176925.00
520      Business Analyst          63000.0              64890.00
545         Data Engineer          80000.0              82400.00
571         Data Engineer         110000.0             113300.00

In [39]:
df_date = df.copy()

In [48]:
def date_str(date):
    year = date.strftime('%Y')
    month = date.strftime('%m')
    day = date.strftime('%d')
    return year + '-' + month + '-' + day

df_date['job_posted_date_str'] = df_date['job_posted_date'].apply(date_str)

df_date[['job_posted_date', 'job_posted_date_str']]

           job_posted_date job_posted_date_str
0      2023-06-16 13:44:15          2023-06-16
1      2023-01-14 13:18:07          2023-01-14
2      2023-10-10 13:14:55          2023-10-10
3      2023-07-04 13:01:41          2023-07-04
4      2023-08-07 14:29:36          2023-08-07
...                    ...                 ...
785736 2023-03-13 06:16:16          2023-03-13
785737 2023-03-12 06:18:18          2023-03-12
785738 2023-03-12 06:32:36          2023-03-12
785739 2023-03-12 06:32:15          2023-03-12
785740 2023-03-13 06:16:31          2023-03-13

[785741 rows x 2 columns]

In [49]:
df_date['job_posted_date_str'] = df_date['job_posted_date'].dt.strftime('%Y-%m-%d')

df_date[['job_posted_date', 'job_posted_date_str']]

           job_posted_date job_posted_date_str
0      2023-06-16 13:44:15          2023-06-16
1      2023-01-14 13:18:07          2023-01-14
2      2023-10-10 13:14:55          2023-10-10
3      2023-07-04 13:01:41          2023-07-04
4      2023-08-07 14:29:36          2023-08-07
...                    ...                 ...
785736 2023-03-13 06:16:16          2023-03-13
785737 2023-03-12 06:18:18          2023-03-12
785738 2023-03-12 06:32:36          2023-03-12
785739 2023-03-12 06:32:15          2023-03-12
785740 2023-03-13 06:16:31          2023-03-13

[785741 rows x 2 columns]

In [62]:
import datetime

df_date['days_since_posted'] = df_date['job_posted_date'].apply(lambda x: (datetime.datetime.now() - x).days)

In [63]:
df_date[['job_posted_date', 'days_since_posted']]

           job_posted_date  days_since_posted
0      2023-06-16 13:44:15               1205
1      2023-01-14 13:18:07               1358
2      2023-10-10 13:14:55               1089
3      2023-07-04 13:01:41               1187
4      2023-08-07 14:29:36               1153
...                    ...                ...
785736 2023-03-13 06:16:16               1301
785737 2023-03-12 06:18:18               1302
785738 2023-03-12 06:32:36               1302
785739 2023-03-12 06:32:15               1302
785740 2023-03-13 06:16:31               1301

[785741 rows x 2 columns]

In [70]:
df_filtered = df[pd.notna(df['salary_year_avg'])].copy()

df_filtered['salary_category'] = df_filtered['salary_year_avg'].apply(lambda salary: 'Low' if salary < 60_000 else 'Medium' if salary < 100_000 else 'High')

df_filtered[['salary_year_avg', 'salary_category']]

        salary_year_avg salary_category
28             109500.0            High
77             140000.0            High
92             120000.0            High
100            228222.0            High
109             89000.0          Medium
...                 ...             ...
785624         139216.0            High
785641         150000.0            High
785648         221875.0            High
785682         157500.0            High
785692         157500.0            High

[22003 rows x 2 columns]